* [[https://devdocs.io][DevDocs]] --- API Documentation Browser
:PROPERTIES:
:CUSTOM_ID: devdocs-api-documentation-browser
:END:
DevDocs combines multiple developer documentations in a clean and
organized web UI with instant search, offline support, mobile version,
dark theme, keyboard shortcuts, and more.

DevDocs was created by [[https://thibaut.me][Thibaut Courouble]] and is
operated by [[https://www.freecodecamp.org][freeCodeCamp]].

** We are currently searching for maintainers
:PROPERTIES:
:CUSTOM_ID: we-are-currently-searching-for-maintainers
:END:
Please reach out to the community on
[[https://discord.gg/PRyKn3Vbay][Discord]] if you would like to join the
team!

Keep track of development news:

- Join the devdocs chat room on
  [[https://discord.gg/PRyKn3Vbay][Discord]]
- Watch the repository on
  [[https://github.com/freeCodeCamp/devdocs/subscription][GitHub]]
- Follow [[https://twitter.com/DevDocs][[cite/t:@DevDocs]]] on Twitter

*Table of Contents:* [[#quick-start][Quick Start]] · [[#vision][Vision]]
· [[#app][App]] · [[#scraper][Scraper]] ·
[[#available-commands][Commands]] · [[#contributing][Contributing]] ·
[[#documentation][Documentation]] · [[#related-projects][Related
Projects]] · [[#copyright--license][License]] ·
[[#questions][Questions?]]

** Quick Start
:PROPERTIES:
:CUSTOM_ID: quick-start
:END:
Unless you wish to contribute to the project, we recommend using the
hosted version at [[https://devdocs.io][devdocs.io]]. It's up-to-date
and works offline out-of-the-box.

DevDocs is made of two pieces: a Ruby scraper that generates the
documentation and metadata, and a JavaScript app powered by a small
Sinatra app.

DevDocs requires Ruby 3.2.1, libcurl, and a JavaScript runtime supported
by [[https://github.com/rails/execjs#readme][ExecJS]] (included in OS X
and Windows; [[https://nodejs.org/en/][Node.js]] on Linux). Once you
have these installed, run the following commands:

#+begin_src sh
git clone https://github.com/freeCodeCamp/devdocs.git && cd devdocs
gem install bundler
bundle install
bundle exec thor docs:download --default
bundle exec rackup
#+end_src

Finally, point your browser at [[http://localhost:9292][localhost:9292]]
(the first request will take a few seconds to compile the assets).
You're all set.

The =thor docs:download= command is used to download pre-generated
documentations from DevDocs's servers
(e.g. =thor docs:download html css=). You can see the list of available
documentations and versions by running =thor docs:list=. To update all
downloaded documentations, run =thor docs:download --installed=. To
download and install all documentation this project has available, run
=thor docs:download --all=.

*Note:* there is currently no update mechanism other than
=git pull origin main= to update the code and
=thor docs:download --installed= to download the latest version of the
docs. To stay informed about new releases, be sure to
[[https://github.com/freeCodeCamp/devdocs/subscription][watch]] this
repository.

Alternatively, DevDocs may be started as a Docker container:

#+begin_src sh
# First, build the image
git clone https://github.com/freeCodeCamp/devdocs.git && cd devdocs
docker build -t thibaut/devdocs .

# Finally, start a DevDocs container (access http://localhost:9292)
docker run --name devdocs -d -p 9292:9292 thibaut/devdocs
#+end_src

** Vision
:PROPERTIES:
:CUSTOM_ID: vision
:END:
DevDocs aims to make reading and searching reference documentation fast,
easy and enjoyable.

The app's main goals are to:

- Keep load times as short as possible
- Improve the quality, speed, and order of search results
- Maximize the use of caching and other performance optimizations
- Maintain a clean and readable user interface
- Be fully functional offline
- Support full keyboard navigation
- Reduce "context switch" by using a consistent typography and design
  across all documentations
- Reduce clutter by focusing on a specific category of content
  (API/reference) and indexing only the minimum useful to most
  developers.

*Note:* DevDocs is neither a programming guide nor a search engine. All
our content is pulled from third-party sources and the project doesn't
intend to compete with full-text search engines. Its backbone is
metadata; each piece of content is identified by a unique, "obvious" and
short string. Tutorials, guides and other content that don't meet this
requirement are outside the scope of the project.

** App
:PROPERTIES:
:CUSTOM_ID: app
:END:
The web app is all client-side JavaScript, written in
[[http://coffeescript.org][CoffeeScript]], and powered by a small
[[http://www.sinatrarb.com][Sinatra]]/[[https://github.com/rails/sprockets][Sprockets]]
application. It relies on files generated by the [[#scraper][scraper]].

Many of the code's design decisions were driven by the fact that the app
uses XHR to load content directly into the main frame. This includes
stripping the original documents of most of their HTML markup
(e.g. scripts and stylesheets) to avoid polluting the main frame, and
prefixing all CSS class names with an underscore to prevent conflicts.

Another driving factor is performance and the fact that everything
happens in the browser. A service worker (which comes with its own set
of constraints) and =localStorage= are used to speed up the boot time,
while memory consumption is kept in check by allowing the user to pick
his/her own set of documentations. The search algorithm is kept simple
because it needs to be fast even searching through 100,000 strings.

DevDocs being a developer tool, the browser requirements are high:

- Recent versions of Firefox, Chrome, or Opera
- Safari 11.1+
- Edge 17+
- iOS 11.3+

This allows the code to take advantage of the latest DOM and HTML5 APIs
and make developing DevDocs a lot more fun!

** Scraper
:PROPERTIES:
:CUSTOM_ID: scraper
:END:
The scraper is responsible for generating the documentation and index
files (metadata) used by the [[#app][app]]. It's written in Ruby under
the =Docs= module.

There are currently two kinds of scrapers: =UrlScraper= which downloads
files via HTTP and =FileScraper= which reads them from the local
filesystem. They both make copies of HTML documents, recursively
following links that match a set of rules and applying all sorts of
modifications along the way, in addition to building an index of the
files and their metadata. Documents are parsed using
[[http://nokogiri.org][Nokogiri]].

Modifications made to each document include:

- removing content such as the document structure (=<html>=, =<head>=,
  etc.), comments, empty nodes, etc.
- fixing links (e.g. to remove duplicates)
- replacing all external (not scraped) URLs with their fully qualified
  counterpart
- replacing all internal (scraped) URLs with their unqualified and
  relative counterpart
- adding content, such as a title and link to the original document
- ensuring correct syntax highlighting using
  [[http://prismjs.com/][Prism]]

These modifications are applied via a set of filters using the
[[https://github.com/jch/html-pipeline][HTML::Pipeline]] library. Each
scraper includes filters specific to itself, one of which is tasked with
figuring out the pages' metadata.

The end result is a set of normalized HTML partials and two JSON files
(index + offline data). Because the index files are loaded separately by
the [[#app][app]] following the user's preferences, the scraper also
creates a JSON manifest file containing information about the
documentations currently available on the system (such as their name,
version, update date, etc.).

More information about [[./docs/scraper-reference.md][scrapers]] and
[[./docs/filter-reference.md][filters]] is available in the =docs=
folder.

** Available Commands
:PROPERTIES:
:CUSTOM_ID: available-commands
:END:
The command-line interface uses [[http://whatisthor.com][Thor]]. To see
all commands and options, run =thor list= from the project's root.

#+begin_src sh
# Server
rackup              # Start the server (ctrl+c to stop)
rackup --help       # List server options

# Docs
thor docs:list      # List available documentations
thor docs:download  # Download one or more documentations
thor docs:manifest  # Create the manifest file used by the app
thor docs:generate  # Generate/scrape a documentation
thor docs:page      # Generate/scrape a documentation page
thor docs:package   # Package a documentation for use with docs:download
thor docs:clean     # Delete documentation packages

# Update

thor updates:check deno

# Console
thor console        # Start a REPL
thor console:docs   # Start a REPL in the "Docs" module

# Tests can be run quickly from within the console using the "test" command.
# Run "help test" for usage instructions.
thor test:all       # Run all tests
thor test:docs      # Run "Docs" tests
thor test:app       # Run "App" tests

# Assets
thor assets:compile # Compile assets (not required in development mode)
thor assets:clean   # Clean old assets
#+end_src

If multiple versions of Ruby are installed on your system, commands must
be run through =bundle exec=.

** Contributing
:PROPERTIES:
:CUSTOM_ID: contributing
:END:
Contributions are welcome. Please read the
[[./.github/CONTRIBUTING.md][contributing guidelines]].

** Documentation
:PROPERTIES:
:CUSTOM_ID: documentation
:END:
- [[./docs/adding-docs.md][Adding documentations to DevDocs]]
- [[./docs/scraper-reference.md][Scraper Reference]]
- [[./docs/filter-reference.md][Filter Reference]]
- [[./docs/maintainers.md][Maintainers' Guide]]

** Related Projects
:PROPERTIES:
:CUSTOM_ID: related-projects
:END:
Made something cool? Feel free to open a PR to add a new row to this
table! You might want to discover new projects via
https://github.com/topics/devdocs.

#+begin_html
  <!-- table is sorted by description -->
#+end_html

| Project                                                                                       | Description                          | Last commit                                                                                     | Stars                                                                                     |
|-----------------------------------------------------------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------|
| [[https://github.com/yannickglt/alfred-devdocs][yannickglt/alfred-devdocs]]                   | Alfred workflow                      | [[https://img.shields.io/github/last-commit/yannickglt/alfred-devdocs?logo=github&label]]       | [[https://img.shields.io/github/stars/yannickglt/alfred-devdocs?logo=github&label]]       |
| [[https://github.com/Merith-TK/devdocs_webapp_kotlin][Merith-TK/devdocs_webapp_kotlin]]       | Android application                  | [[https://img.shields.io/github/last-commit/Merith-TK/devdocs_webapp_kotlin?logo=github&label]] | [[https://img.shields.io/github/stars/Merith-TK/devdocs_webapp_kotlin?logo=github&label]] |
| [[https://github.com/gruehle/dev-docs-viewer][gruehle/dev-docs-viewer]]                       | Brackets extension                   | [[https://img.shields.io/github/last-commit/gruehle/dev-docs-viewer?logo=github&label]]         | [[https://img.shields.io/github/stars/gruehle/dev-docs-viewer?logo=github&label]]         |
| [[https://github.com/egoist/devdocs-desktop][egoist/devdocs-desktop]]                         | Electron application                 | [[https://img.shields.io/github/last-commit/egoist/devdocs-desktop?logo=github&label]]          | [[https://img.shields.io/github/stars/egoist/devdocs-desktop?logo=github&label]]          |
| [[https://github.com/skeeto/devdocs-lookup][skeeto/devdocs-lookup]]                           | Emacs function                       | [[https://img.shields.io/github/last-commit/skeeto/devdocs-lookup?logo=github&label]]           | [[https://img.shields.io/github/stars/skeeto/devdocs-lookup?logo=github&label]]           |
| [[https://github.com/astoff/devdocs.el][astoff/devdocs.el]]                                   | Emacs viewer                         | [[https://img.shields.io/github/last-commit/astoff/devdocs.el?logo=github&label]]               | [[https://img.shields.io/github/stars/astoff/devdocs.el?logo=github&label]]               |
| [[https://github.com/naquad/devdocs-shell][naquad/devdocs-shell]]                             | GTK shell with Vim integration       | [[https://img.shields.io/github/last-commit/naquad/devdocs-shell?logo=github&label]]            | [[https://img.shields.io/github/stars/naquad/devdocs-shell?logo=github&label]]            |
| [[https://github.com/hardpixel/devdocs-desktop][hardpixel/devdocs-desktop]]                   | GTK application                      | [[https://img.shields.io/github/last-commit/hardpixel/devdocs-desktop?logo=github&label]]       | [[https://img.shields.io/github/stars/hardpixel/devdocs-desktop?logo=github&label]]       |
| [[https://github.com/qwfy/doc-browser][qwfy/doc-browser]]                                     | Linux application                    | [[https://img.shields.io/github/last-commit/qwfy/doc-browser?logo=github&label]]                | [[https://img.shields.io/github/stars/qwfy/doc-browser?logo=github&label]]                |
| [[https://github.com/dteoh/devdocs-macos][dteoh/devdocs-macos]]                               | macOS application                    | [[https://img.shields.io/github/last-commit/dteoh/devdocs-macos?logo=github&label]]             | [[https://img.shields.io/github/stars/dteoh/devdocs-macos?logo=github&label]]             |
| [[https://sublime.wbond.net/packages/DevDocs][Sublime Text plugin]]                           | Sublime Text plugin                  | [[https://img.shields.io/github/last-commit/vitorbritto/sublime-devdocs?logo=github&label]]     | [[https://img.shields.io/github/stars/vitorbritto/sublime-devdocs?logo=github&label]]     |
| [[https://github.com/mohamed3nan/DevDocs-Tab][mohamed3nan/DevDocs-Tab]]                       | VS Code extension (view as tab)      | [[https://img.shields.io/github/last-commit/mohamed3nan/DevDocs-Tab?logo=github&label]]         | [[https://img.shields.io/github/stars/mohamed3nan/DevDocs-Tab?logo=github&label]]         |
| [[https://marketplace.visualstudio.com/items?itemName=deibit.devdocs][deibit/vscode-devdocs]] | VS Code extension (open the browser) | [[https://img.shields.io/github/last-commit/deibit/vscode-devdocs?logo=github&label]]           | [[https://img.shields.io/github/stars/deibit/vscode-devdocs?logo=github&label]]           |
| [[https://github.com/mdh34/quickDocs][mdh34/quickDocs]]                                       | Vala/Python based viewer             | [[https://img.shields.io/github/last-commit/mdh34/quickDocs?logo=github&label]]                 | [[https://img.shields.io/github/stars/mdh34/quickDocs?logo=github&label]]                 |
| [[https://github.com/romainl/vim-devdocs][romainl/vim-devdocs]]                               | Vim plugin                           | [[https://img.shields.io/github/last-commit/romainl/vim-devdocs?logo=github&label]]             | [[https://img.shields.io/github/stars/romainl/vim-devdocs?logo=github&label]]             |
| [[https://github.com/waiting-for-dev/vim-www][waiting-for-dev/vim-www]]                       | Vim plugin                           | [[https://img.shields.io/github/last-commit/waiting-for-dev/vim-www?logo=github&label]]         | [[https://img.shields.io/github/stars/waiting-for-dev/vim-www?logo=github&label]]         |

** Copyright / License
:PROPERTIES:
:CUSTOM_ID: copyright-license
:END:
Copyright 2013--2023 Thibaut Courouble and
[[https://github.com/freeCodeCamp/devdocs/graphs/contributors][other
contributors]]

This software is licensed under the terms of the Mozilla Public License
v2.0. See the [[./COPYRIGHT][COPYRIGHT]] and [[./LICENSE][LICENSE]]
files.

Please do not use the name DevDocs to endorse or promote products
derived from this software without the maintainers' permission, except
as may be necessary to comply with the notice/attribution requirements.

We also wish that any documentation file generated using this software
be attributed to DevDocs. Let's be fair to all contributors by giving
credit where credit's due. Thanks!

** Questions?
:PROPERTIES:
:CUSTOM_ID: questions
:END:
If you have any questions, please feel free to ask them on the
contributor chat room on [[https://discord.gg/PRyKn3Vbay][Discord]].
